import type {
  DemoRole,
  DemoSystemCheck,
  DemoTenant,
} from "@/domain/demo/admin-types";

export const DEMO_ROLES: readonly DemoRole[] = [
  {
    id: "broker",
    label: "Corredor B & B — DEMO",
    shortLabel: "Corredor",
    description: "Gestiona su cartera y prepara publicaciones asignadas.",
    boundary: "No puede aprobar su propia publicación ni ver otra corredora.",
    allowedSections: [
      "dashboard",
      "clients",
      "assets",
      "publications",
      "leads",
      "audit",
    ],
  },
  {
    id: "agency-admin",
    label: "Administrador de corredora — DEMO",
    shortLabel: "Admin corredora",
    description: "Supervisa la operación y aprueba publicaciones de su empresa.",
    boundary: "La selección de empresa es visual; no demuestra autorización real.",
    allowedSections: [
      "dashboard",
      "clients",
      "assets",
      "publications",
      "leads",
      "audit",
    ],
  },
  {
    id: "platform-admin",
    label: "Administrador de plataforma — DEMO",
    shortLabel: "Admin plataforma",
    description: "Observa salud y métricas agregadas de las corredoras.",
    boundary: "No dispone de acceso comercial permanente a clientes o activos.",
    allowedSections: ["dashboard", "tenants", "audit"],
  },
  {
    id: "system-admin",
    label: "Administrador técnico / SGBD — DEMO",
    shortLabel: "Admin técnico",
    description: "Visualiza arquitectura futura, respaldos y controles técnicos.",
    boundary: "No navega información comercial ni administra una base real.",
    allowedSections: ["dashboard", "system", "audit"],
  },
] as const;

export const DEMO_TENANTS: readonly DemoTenant[] = [
  {
    id: "bb-demo",
    name: "B & B Corretaje · DEMO",
    area: "Los Ángeles y provincia de Biobío",
    status: "Piloto DEMO",
    members: 4,
    clients: [
      {
        id: "CLI-DEMO-BB-01",
        alias: "Cliente DEMO A-01",
        requirement: "Vender vivienda urbana",
        operation: "Venta",
        stage: "En negociación",
        assignedTeam: "Equipo residencial DEMO",
        nextAction: "Revisar propuesta comercial ficticia",
      },
      {
        id: "CLI-DEMO-BB-02",
        alias: "Cliente DEMO A-02",
        requirement: "Dar departamento en arriendo",
        operation: "Arriendo",
        stage: "Calificado",
        assignedTeam: "Equipo residencial DEMO",
        nextAction: "Completar antecedentes sintéticos",
      },
      {
        id: "CLI-DEMO-BB-03",
        alias: "Cliente DEMO A-03",
        requirement: "Buscar parcela familiar",
        operation: "Compra",
        stage: "En búsqueda",
        assignedTeam: "Equipo rural DEMO",
        nextAction: "Comparar alternativas DEMO",
      },
      {
        id: "CLI-DEMO-BB-04",
        alias: "Cliente DEMO A-04",
        requirement: "Presentar predio productivo",
        operation: "Intermediación",
        stage: "Calificado",
        assignedTeam: "Activos especiales DEMO",
        nextAction: "Definir información publicable",
      },
      {
        id: "CLI-DEMO-BB-05",
        alias: "Cliente DEMO A-05",
        requirement: "Buscar arriendo urbano",
        operation: "Arriendo",
        stage: "Nuevo",
        assignedTeam: "Equipo residencial DEMO",
        nextAction: "Realizar contacto humano futuro",
      },
      {
        id: "CLI-DEMO-BB-06",
        alias: "Cliente DEMO A-06",
        requirement: "Vender lote residencial",
        operation: "Venta",
        stage: "En negociación",
        assignedTeam: "Equipo suelo DEMO",
        nextAction: "Registrar resultado simulado",
      },
    ],
    assets: [
      {
        id: "ACT-DEMO-BB-01",
        label: "Casa familiar de líneas cálidas",
        propertyType: "Casa",
        operation: "Venta",
        commune: "Los Ángeles",
        stage: "En gestión",
        completeness: 100,
        assignedTeam: "Equipo residencial DEMO",
      },
      {
        id: "ACT-DEMO-BB-02",
        label: "Departamento luminoso y funcional",
        propertyType: "Departamento",
        operation: "Arriendo",
        commune: "Los Ángeles",
        stage: "En gestión",
        completeness: 96,
        assignedTeam: "Equipo residencial DEMO",
      },
      {
        id: "ACT-DEMO-BB-03",
        label: "Parcela con casa y entorno abierto",
        propertyType: "Parcela",
        operation: "Venta",
        commune: "Santa Bárbara",
        stage: "Publicable",
        completeness: 88,
        assignedTeam: "Equipo rural DEMO",
      },
      {
        id: "ACT-DEMO-BB-04",
        label: "Predio productivo de escala mayor",
        propertyType: "Predio productivo",
        operation: "Activo especial",
        commune: "Mulchén",
        stage: "En gestión",
        completeness: 92,
        assignedTeam: "Activos especiales DEMO",
      },
      {
        id: "ACT-DEMO-BB-05",
        label: "Bodega urbana de ejemplo",
        propertyType: "Bodega",
        operation: "Arriendo",
        commune: "Los Ángeles",
        stage: "En revisión",
        completeness: 64,
        assignedTeam: "Equipo comercial DEMO",
      },
      {
        id: "ACT-DEMO-BB-06",
        label: "Lote residencial ficticio",
        propertyType: "Terreno",
        operation: "Venta",
        commune: "Nacimiento",
        stage: "Captación",
        completeness: 38,
        assignedTeam: "Equipo suelo DEMO",
      },
      {
        id: "ACT-DEMO-BB-07",
        label: "Vivienda compacta de muestra",
        propertyType: "Casa",
        operation: "Venta",
        commune: "Cabrero",
        stage: "En revisión",
        completeness: 71,
        assignedTeam: "Equipo residencial DEMO",
      },
    ],
    publications: [
      {
        id: "PUB-DEMO-BB-01",
        title: "Casa familiar de líneas cálidas",
        assetId: "ACT-DEMO-BB-01",
        status: "active",
        startsOn: "01-08-2026",
        endsOn: "30-10-2026",
        durationDays: 90,
        elapsedDays: 28,
        channel: "Sitio B & B DEMO",
      },
      {
        id: "PUB-DEMO-BB-02",
        title: "Departamento luminoso y funcional",
        assetId: "ACT-DEMO-BB-02",
        status: "active",
        startsOn: "15-08-2026",
        endsOn: "29-09-2026",
        durationDays: 45,
        elapsedDays: 14,
        channel: "Sitio B & B DEMO",
      },
      {
        id: "PUB-DEMO-BB-03",
        title: "Parcela con casa y entorno abierto",
        assetId: "ACT-DEMO-BB-03",
        status: "active",
        startsOn: "20-08-2026",
        endsOn: "18-11-2026",
        durationDays: 90,
        elapsedDays: 9,
        channel: "Sitio B & B DEMO",
      },
      {
        id: "PUB-DEMO-BB-04",
        title: "Predio productivo de escala mayor",
        assetId: "ACT-DEMO-BB-04",
        status: "active",
        startsOn: "22-08-2026",
        endsOn: "20-12-2026",
        durationDays: 120,
        elapsedDays: 7,
        channel: "Sitio B & B DEMO",
      },
      {
        id: "PUB-DEMO-BB-05",
        title: "Bodega urbana de ejemplo",
        assetId: "ACT-DEMO-BB-05",
        status: "pending-review",
        startsOn: "Pendiente",
        endsOn: "Pendiente",
        durationDays: 60,
        elapsedDays: 0,
        channel: "Borrador interno DEMO",
      },
      {
        id: "PUB-DEMO-BB-06",
        title: "Lote residencial ficticio",
        assetId: "ACT-DEMO-BB-06",
        status: "draft",
        startsOn: "Pendiente",
        endsOn: "Pendiente",
        durationDays: 90,
        elapsedDays: 0,
        channel: "Borrador interno DEMO",
      },
      {
        id: "PUB-DEMO-BB-07",
        title: "Vivienda compacta de muestra",
        assetId: "ACT-DEMO-BB-07",
        status: "expired",
        startsOn: "01-06-2026",
        endsOn: "30-07-2026",
        durationDays: 60,
        elapsedDays: 60,
        channel: "Borrador interno DEMO",
      },
    ],
    leads: [
      {
        id: "LEAD-DEMO-BB-01",
        alias: "Interesado DEMO L-01",
        interest: "Casa urbana ficticia",
        stage: "Seguimiento",
        source: "Sitio DEMO",
        ageDays: 2,
        nextAction: "Coordinar visita simulada",
      },
      {
        id: "LEAD-DEMO-BB-02",
        alias: "Interesado DEMO L-02",
        interest: "Departamento de muestra",
        stage: "Contactado",
        source: "Referencia DEMO",
        ageDays: 1,
        nextAction: "Registrar respuesta ficticia",
      },
      {
        id: "LEAD-DEMO-BB-03",
        alias: "Interesado DEMO L-03",
        interest: "Parcela rural ficticia",
        stage: "Visita DEMO",
        source: "Oficina DEMO",
        ageDays: 4,
        nextAction: "Preparar recorrido DEMO",
      },
      {
        id: "LEAD-DEMO-BB-04",
        alias: "Interesado DEMO L-04",
        interest: "Activo especial ficticio",
        stage: "Nuevo",
        source: "Sitio DEMO",
        ageDays: 0,
        nextAction: "Calificar interés sin datos reales",
      },
      {
        id: "LEAD-DEMO-BB-05",
        alias: "Interesado DEMO L-05",
        interest: "Lote residencial ficticio",
        stage: "Seguimiento",
        source: "Referencia DEMO",
        ageDays: 6,
        nextAction: "Cerrar actividad demostrativa",
      },
    ],
    auditEvents: [
      {
        id: "AUD-DEMO-BB-01",
        occurredAt: "29 ago · 09:40",
        actorRole: "Admin corredora DEMO",
        action: "Revisó proyección pública",
        scope: "PUB-DEMO-BB-03",
        result: "Revisado",
      },
      {
        id: "AUD-DEMO-BB-02",
        occurredAt: "29 ago · 09:15",
        actorRole: "Corredor DEMO",
        action: "Preparó borrador",
        scope: "PUB-DEMO-BB-05",
        result: "Registrado",
      },
      {
        id: "AUD-DEMO-BB-03",
        occurredAt: "28 ago · 17:30",
        actorRole: "Control DEMO",
        action: "Bloqueó aprobación propia",
        scope: "PUB-DEMO-BB-05",
        result: "Bloqueado",
      },
      {
        id: "AUD-DEMO-BB-04",
        occurredAt: "28 ago · 16:05",
        actorRole: "Admin corredora DEMO",
        action: "Actualizó duración",
        scope: "PUB-DEMO-BB-02",
        result: "Registrado",
      },
    ],
  },
  {
    id: "cordillera-demo",
    name: "Corretaje Cordillera · DEMO",
    area: "Escenario colaborador del Biobío",
    status: "Escenario DEMO",
    members: 3,
    clients: [
      {
        id: "CLI-DEMO-CD-01",
        alias: "Cliente DEMO C-01",
        requirement: "Comprar vivienda familiar",
        operation: "Compra",
        stage: "En búsqueda",
        assignedTeam: "Equipo Cordillera DEMO",
        nextAction: "Revisar selección ficticia",
      },
      {
        id: "CLI-DEMO-CD-02",
        alias: "Cliente DEMO C-02",
        requirement: "Dar local en arriendo",
        operation: "Arriendo",
        stage: "Calificado",
        assignedTeam: "Equipo Cordillera DEMO",
        nextAction: "Preparar presentación DEMO",
      },
      {
        id: "CLI-DEMO-CD-03",
        alias: "Cliente DEMO C-03",
        requirement: "Vender terreno rural",
        operation: "Venta",
        stage: "Nuevo",
        assignedTeam: "Equipo Cordillera DEMO",
        nextAction: "Revisión humana futura",
      },
      {
        id: "CLI-DEMO-CD-04",
        alias: "Cliente DEMO C-04",
        requirement: "Arrendar departamento",
        operation: "Arriendo",
        stage: "En negociación",
        assignedTeam: "Equipo Cordillera DEMO",
        nextAction: "Registrar avance simulado",
      },
    ],
    assets: [
      {
        id: "ACT-DEMO-CD-01",
        label: "Casa cordillerana de muestra",
        propertyType: "Casa",
        operation: "Venta",
        commune: "Quilleco",
        stage: "Publicable",
        completeness: 90,
        assignedTeam: "Equipo Cordillera DEMO",
      },
      {
        id: "ACT-DEMO-CD-02",
        label: "Local comercial ficticio",
        propertyType: "Local",
        operation: "Arriendo",
        commune: "Los Ángeles",
        stage: "En gestión",
        completeness: 84,
        assignedTeam: "Equipo Cordillera DEMO",
      },
      {
        id: "ACT-DEMO-CD-03",
        label: "Terreno rural de ejemplo",
        propertyType: "Terreno",
        operation: "Venta",
        commune: "Tucapel",
        stage: "En revisión",
        completeness: 58,
        assignedTeam: "Equipo Cordillera DEMO",
      },
      {
        id: "ACT-DEMO-CD-04",
        label: "Departamento compacto ficticio",
        propertyType: "Departamento",
        operation: "Arriendo",
        commune: "Los Ángeles",
        stage: "Captación",
        completeness: 41,
        assignedTeam: "Equipo Cordillera DEMO",
      },
    ],
    publications: [
      {
        id: "PUB-DEMO-CD-01",
        title: "Casa cordillerana de muestra",
        assetId: "ACT-DEMO-CD-01",
        status: "approved",
        startsOn: "Pendiente",
        endsOn: "Pendiente",
        durationDays: 90,
        elapsedDays: 0,
        channel: "Borrador interno DEMO",
      },
      {
        id: "PUB-DEMO-CD-02",
        title: "Local comercial ficticio",
        assetId: "ACT-DEMO-CD-02",
        status: "active",
        startsOn: "10-08-2026",
        endsOn: "08-10-2026",
        durationDays: 60,
        elapsedDays: 19,
        channel: "Sitio B & B DEMO",
      },
      {
        id: "PUB-DEMO-CD-03",
        title: "Terreno rural de ejemplo",
        assetId: "ACT-DEMO-CD-03",
        status: "paused",
        startsOn: "01-08-2026",
        endsOn: "29-10-2026",
        durationDays: 90,
        elapsedDays: 28,
        channel: "Borrador interno DEMO",
      },
      {
        id: "PUB-DEMO-CD-04",
        title: "Departamento compacto ficticio",
        assetId: "ACT-DEMO-CD-04",
        status: "draft",
        startsOn: "Pendiente",
        endsOn: "Pendiente",
        durationDays: 45,
        elapsedDays: 0,
        channel: "Borrador interno DEMO",
      },
      {
        id: "PUB-DEMO-CD-05",
        title: "Parcela de cierre demostrativo",
        assetId: "ACT-DEMO-CD-03",
        status: "sold",
        startsOn: "01-05-2026",
        endsOn: "29-07-2026",
        durationDays: 90,
        elapsedDays: 74,
        channel: "Borrador interno DEMO",
      },
    ],
    leads: [
      {
        id: "LEAD-DEMO-CD-01",
        alias: "Interesado DEMO C-L1",
        interest: "Casa cordillerana ficticia",
        stage: "Contactado",
        source: "Sitio DEMO",
        ageDays: 1,
        nextAction: "Seguimiento demostrativo",
      },
      {
        id: "LEAD-DEMO-CD-02",
        alias: "Interesado DEMO C-L2",
        interest: "Local comercial ficticio",
        stage: "Nuevo",
        source: "Oficina DEMO",
        ageDays: 0,
        nextAction: "Calificar sin datos personales",
      },
      {
        id: "LEAD-DEMO-CD-03",
        alias: "Interesado DEMO C-L3",
        interest: "Terreno rural de ejemplo",
        stage: "Seguimiento",
        source: "Referencia DEMO",
        ageDays: 5,
        nextAction: "Cerrar actividad DEMO",
      },
    ],
    auditEvents: [
      {
        id: "AUD-DEMO-CD-01",
        occurredAt: "29 ago · 08:50",
        actorRole: "Admin corredora DEMO",
        action: "Aprobó contenido sintético",
        scope: "PUB-DEMO-CD-01",
        result: "Registrado",
      },
      {
        id: "AUD-DEMO-CD-02",
        occurredAt: "28 ago · 15:20",
        actorRole: "Corredor DEMO",
        action: "Pausó publicación",
        scope: "PUB-DEMO-CD-03",
        result: "Registrado",
      },
      {
        id: "AUD-DEMO-CD-03",
        occurredAt: "28 ago · 14:10",
        actorRole: "Control DEMO",
        action: "Separó datos por escenario",
        scope: "CORREDORA-DEMO-CD",
        result: "Revisado",
      },
    ],
  },
] as const;

export const DEMO_SYSTEM_CHECKS: readonly DemoSystemCheck[] = [
  {
    id: "SYS-DEMO-01",
    component: "API segura y versionada",
    futurePurpose: "Autorizar cada solicitud desde web, PWA y escritorio.",
    state: "No implementado",
    note: "P1.4 no realiza llamadas de red.",
  },
  {
    id: "SYS-DEMO-02",
    component: "PostgreSQL privado",
    futurePurpose: "Conservar clientes, activos, relaciones y auditoría.",
    state: "Diseñado",
    note: "Sólo existe el modelo conceptual; no hay SGBD local ni remoto.",
  },
  {
    id: "SYS-DEMO-03",
    component: "Aislamiento RLS por corredora",
    futurePurpose: "Impedir consultas cruzadas entre empresas.",
    state: "Bloqueado",
    note: "Requiere MVP, pruebas cruzadas y revisión AppSec independiente.",
  },
  {
    id: "SYS-DEMO-04",
    component: "Respaldos y restauración",
    futurePurpose: "Recuperar información ante error o incidente.",
    state: "No implementado",
    note: "Los datos DEMO actuales se recrean desde código.",
  },
  {
    id: "SYS-DEMO-05",
    component: "Almacenamiento privado",
    futurePurpose: "Proteger documentos y fotografías no publicables.",
    state: "Bloqueado",
    note: "P1.4 no admite archivos ni documentos.",
  },
  {
    id: "SYS-DEMO-06",
    component: "Monitoreo y alertas",
    futurePurpose: "Detectar fallas, abuso y eventos de seguridad.",
    state: "Diseñado",
    note: "La vista actual sólo comunica el alcance futuro.",
  },
] as const;

export const DEMO_PLATFORM_AUDIT = [
  {
    id: "AUD-DEMO-PLAT-01",
    occurredAt: "29 ago · 10:10",
    actorRole: "Plataforma DEMO",
    action: "Calculó métricas agregadas",
    scope: "2 corredoras DEMO",
    result: "Registrado" as const,
  },
  {
    id: "AUD-DEMO-PLAT-02",
    occurredAt: "29 ago · 10:00",
    actorRole: "Control de acceso futuro",
    action: "Rechazó lectura comercial global",
    scope: "Regla de mínimo privilegio",
    result: "Bloqueado" as const,
  },
  {
    id: "AUD-DEMO-PLAT-03",
    occurredAt: "29 ago · 09:55",
    actorRole: "Sistema DEMO",
    action: "Revisó estado conceptual",
    scope: "Sin conexión a SGBD",
    result: "Revisado" as const,
  },
] as const;
